[package]
name = "navcat"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.29.0"
clap = { version = "4.5", features = ["derive"] }
tempfile = "3.20.0"
lazy_static = "1.4"
